[package]
name = "diary_app_bot"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.6"
diary_app_lib = {path="../diary_app_lib"}
failure = "0.1"
log = "0.4"
env_logger = "0.7"
futures = "0.1"
crossbeam-channel = "0.4"
parking_lot = "0.10"
crossbeam-utils = "0.7"
lazy_static = "1.4"
tokio-core = "0.1"
actix-rt = "0.2"
