[package]
name = "diary_app_rust"
version = "0.1.1"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8"
r2d2_postgres = "0.14"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
failure = "0.1"
chrono = "0.4"
rusoto_core = {version = "0.39", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.39", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.39" }
rand = "0.6"
log = "0.4"
env_logger = "0.6"
url = "2.1"
dotenv = "0.14"
futures = "0.1"
rayon = "1.1"
jwalk = "0.4"

[[bin]]
name = "diary-app-rust"
path = "src/main.rs"
doc = false
