[package]
name = "diary_app_rust"
version = "0.1.45"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diary_app_lib = {path="diary_app_lib"}
diary_app_api = {path="diary_app_api"}
failure = "0.1"
log = "0.4"
env_logger = "0.7"
futures = "0.1"
crossbeam-channel = "0.3"
parking_lot = "0.9"
crossbeam-utils = "0.6"
lazy_static = "1.4"
telegram-bot = "0.6"
tokio-core = "0.1"
actix-rt = "0.2"

[workspace]
members = [
    "diary_app_lib",
    "diary_app_api",
]

[[bin]]
name = "diary-app-rust"
path = "src/diary_app_rust.rs"
doc = false

[[bin]]
name = "diary-app-bot"
path = "src/telegram_bot.rs"
doc = false

[[bin]]
name = "diary-app-api"
path = "src/diary_app_api.rs"
doc = false
