[package]
name = "diary_app_api"
version = "0.1.21"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
actix = "0.8.3"
actix-identity = "0.1"
actix-rt = "0.2"
diary_app_lib = {path = "../diary_app_lib"}
failure = "0.1"
chrono = "0.4"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
jsonwebtoken = "6.0"
lazy_static = "1.4"
tokio-timer = "0.2"
log = "0.4"
parking_lot = "0.9"
maplit = "1.0"
