[package]
name = "diary_app_api"
version = "0.5.25"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diary_app_lib = {path = "../diary_app_lib"}
actix-web = "3.2"
actix-identity = "0.3"
actix-rt = "1.1"
chrono = "0.4"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="0.2", features=["time"]}
log = "0.4"
parking_lot = "0.11"
maplit = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
handlebars = "3.5"
itertools = "0.9"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.9", features=["diesel_types"] }
authorized_users = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.2.5"}

[dev-dependencies]
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"]}
auth_server_http = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.2.5"}
auth_server_lib = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.2.5"}
