[package]
name = "diary_app_api"
version = "0.7.5"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diary_app_lib = {path = "../diary_app_lib"}
rweb = {version="0.12", features=["openapi"]}
http = "0.2"
chrono = "0.4"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="1.6", features=["time"]}
log = "0.4"
parking_lot = "0.11"
maplit = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
handlebars = "4.0"
itertools = "0.10"
indexmap = "1.6"
serde_yaml = "0.8"
rweb_helper = { git = "https://github.com/ddboline/rweb_helper.git", tag="0.2.2" }
stack-string = { version="0.2", features=["diesel_types", "rweb-openapi"] }
authorized_users = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.5.4"}

[dev-dependencies]
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"]}
auth_server_http = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.5.4"}
auth_server_lib = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.5.4"}
env_logger = "0.8"