openapi: 3.0.1
info:
  title: Frontend for AWS
  description: Web Frontend for AWS Services
  version: 0.10.6
paths:
  /api/search:
    get:
      description: Search Output Page
      parameters:
      - name: text
        in: query
        required: false
        schema:
          description: Search Text
          nullable: true
          type: string
      - name: date
        in: query
        required: false
        schema:
          description: Search Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      responses:
        '200':
          description: Search Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/insert:
    post:
      description: Insert Text into Cache
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertData'
        required: true
      responses:
        '201':
          description: Insert Data Result
          content:
            application/json:
              schema:
                properties:
                  datetime:
                    type: string
                type: object
                required:
                - datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/sync:
    post:
      description: Sync Diary
      responses:
        '200':
          description: Sync Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/replace:
    post:
      description: Insert Text at Specific Date, replace existing text
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplaceData'
        required: true
      responses:
        '201':
          description: Replace Response
          content:
            application/json:
              schema:
                properties:
                  entry:
                    type: string
                type: object
                required:
                - entry
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/list:
    get:
      description: List of Date Buttons
      parameters:
      - name: min_date
        in: query
        required: false
        schema:
          description: Minimum Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: max_date
        in: query
        required: false
        schema:
          description: Maximum Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: start
        in: query
        required: false
        schema:
          description: Start Index
          nullable: true
          type: integer
          minimum: 0
      - name: limit
        in: query
        required: false
        schema:
          description: Limit
          nullable: true
          type: integer
          minimum: 0
      responses:
        '200':
          description: List Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/edit:
    get:
      description: Diary Edit Form
      parameters:
      - name: date
        in: query
        required: true
        schema:
          format: date
          example: 2023-01-01
          type: string
      responses:
        '200':
          description: Edit Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/display:
    get:
      description: Display Diary Entry
      parameters:
      - name: date
        in: query
        required: true
        schema:
          format: date
          example: 2023-01-01
          type: string
      responses:
        '200':
          description: Display Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/index.html:
    get:
      description: Diary Main Page
      responses:
        '200':
          description: Frontpage
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/list_conflicts:
    get:
      description: List Conflicts
      parameters:
      - name: date
        in: query
        required: false
        schema:
          description: Conflict Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: datetime
        in: query
        required: false
        schema:
          description: Conflict DateTime
          format: date-time
          nullable: true
          type: string
      responses:
        '200':
          description: List Conflicts
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/show_conflict:
    get:
      description: Show Conflict
      parameters:
      - name: date
        in: query
        required: false
        schema:
          description: Conflict Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: datetime
        in: query
        required: false
        schema:
          description: Conflict DateTime
          format: date-time
          nullable: true
          type: string
      responses:
        '200':
          description: Show Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/remove_conflict:
    delete:
      description: Delete Conflict
      parameters:
      - name: date
        in: query
        required: false
        schema:
          description: Conflict Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: datetime
        in: query
        required: false
        schema:
          description: Conflict DateTime
          format: date-time
          nullable: true
          type: string
      responses:
        '200':
          description: Remove Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/update_conflict:
    patch:
      description: Update Conflict
      parameters:
      - name: id
        in: query
        required: true
        schema:
          description: Conflict ID
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
      - name: diff_type
        in: query
        required: true
        schema:
          description: Difference Type
          type: string
      responses:
        '200':
          description: Update Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/commit_conflict:
    post:
      description: Commit Conflict
      parameters:
      - name: datetime
        in: query
        required: true
        schema:
          format: date-time
          type: string
      responses:
        '200':
          description: Commit Conflict
          content:
            application/json:
              schema:
                properties:
                  entry:
                    type: string
                type: object
                required:
                - entry
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/user:
    get:
      description: Get User Object
      responses:
        '200':
          description: Logged in User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedUser'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    InsertData:
      properties:
        text:
          description: Text to Insert
          type: string
      type: object
      required:
      - text
    ReplaceData:
      properties:
        date:
          description: Replacement Date
          format: date
          example: 2023-01-01
          type: string
        text:
          description: Replacement Text
          type: string
      type: object
      required:
      - date
      - text
    ConflictData:
      properties:
        date:
          description: Conflict Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
        datetime:
          description: Conflict DateTime
          format: date-time
          nullable: true
          type: string
      type: object
    LoggedUser:
      properties:
        email:
          description: Email Address
          type: string
        session:
          description: Session Id
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
      type: object
      required:
      - email
      - session
