openapi: '3.1.0'
info:
  title: Frontend for Diary
  description: Web Frontend for Diary Service
  contact:
    name: Daniel Boline
    email: ddboline@gmail.com
  license:
    name: MIT
    identifier: MIT
  version: '0.12.1'
paths:
  /api/commit_conflict:
    post:
      operationId: commit_conflict
      parameters:
      - name: datetime
        in: query
        required: true
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Commit Conflict
          content:
            text/html:
              schema:
                type: object
                required:
                - entry
                properties:
                  entry:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/display:
    get:
      operationId: display
      parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: Display Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/edit:
    get:
      operationId: edit
      parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: Edit Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/index.html:
    get:
      operationId: diary_frontpage
      responses:
        '200':
          description: Frontpage
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/insert:
    post:
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertData'
        required: true
      responses:
        '201':
          description: Insert Data Result
          content:
            text/html:
              schema:
                type: object
                required:
                - datetime
                properties:
                  datetime:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/list:
    get:
      operationId: list
      parameters:
      - name: min_date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: max_date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: start
        in: query
        required: false
        schema:
          type:
          - integer
          - 'null'
          minimum: 0
      - name: limit
        in: query
        required: false
        schema:
          type:
          - integer
          - 'null'
          minimum: 0
      responses:
        '200':
          description: List Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/list_conflicts:
    get:
      operationId: list_conflicts
      parameters:
      - name: date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: datetime
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: List Conflicts
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/remove_conflict:
    delete:
      operationId: remove_conflict
      parameters:
      - name: date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: datetime
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Remove Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/replace:
    post:
      operationId: replace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplaceData'
        required: true
      responses:
        '201':
          description: Replace Response
          content:
            text/html:
              schema:
                type: object
                required:
                - entry
                properties:
                  entry:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/search:
    get:
      operationId: search
      parameters:
      - name: text
        in: query
        required: false
        schema:
          oneOf:
          - type: 'null'
          - type: string
      - name: date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      responses:
        '200':
          description: Search Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/show_conflict:
    get:
      operationId: show_conflict
      parameters:
      - name: date
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date
      - name: datetime
        in: query
        required: false
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Show Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/sync:
    post:
      operationId: sync
      responses:
        '200':
          description: Sync Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/update_conflict:
    patch:
      operationId: update_conflict
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: diff_type
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Update Conflict
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
  /api/user:
    get:
      operationId: user
      responses:
        '200':
          description: Logged in User
          content:
            text/html:
              schema:
                type: object
                required:
                - email
                - session
                - created_at
                properties:
                  created_at:
                    type: string
                    format: date-time
                  email:
                    type: string
                  session:
                    type: string
                    format: uuid
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
components:
  schemas:
    InsertData:
      type: object
      required:
      - text
      properties:
        text:
          type: string
    LoggedUser:
      type: object
      required:
      - email
      - session
      - created_at
      properties:
        created_at:
          type: string
          format: date-time
        email:
          type: string
        session:
          type: string
          format: uuid
    ReplaceData:
      type: object
      required:
      - date
      - text
      properties:
        date:
          type: string
          format: date
        text:
          $ref: '#/components/schemas/str'
    str:
      type: string
