[package]
name = "diary_app_lib"
version = "0.5.23"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
chrono = "0.4"
rusoto_core = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.45", default_features = false, features=["rustls"]}
sts_profile_auth = "0.5"
s3-ext = "0.1"
rand = "0.7"
log = "0.4"
url = "2.1"
dotenv = "0.15"
futures = "0.3"
rayon = "1.5"
jwalk = "0.5"
structopt = "0.3"
crossbeam-channel = "0.5"
parking_lot = "0.11"
crossbeam-utils = "0.8"
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = {version = "1.4", default_features = false}
difference = "2.0"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0"
tokio = {version="0.2", features=["full"]}
derive_more = "0.99"
envy = "0.4"
smartstring = "0.2"
smallvec = "1.4"
deadqueue = "0.1"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.7", features=["diesel_types"] }

[dev-dependencies]
tempdir = "0.3"
