[package]
name = "diary_app_lib"
version = "0.2.3"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
r2d2 = "0.8"
r2d2_postgres = "0.16"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
failure = "0.1"
chrono = "0.4"
rusoto_core = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.42", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.42" }
rand = "0.7"
log = "0.4"
env_logger = "0.7"
url = "2.1"
dotenv = "0.15"
futures = "0.3"
rayon = "1.3"
jwalk = "0.4"
structopt = "0.3"
crossbeam-channel = "0.4"
parking_lot = "0.10"
crossbeam-utils = "0.7"
lazy_static = "1.4"
telegram-bot = "0.6"
tokio-core = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
subprocess = "0.1"
regex = {version = "1.3", default_features = false}
difference = "2.0"
retry ="0.5"
tempdir = "0.3"
