[package]
name = "diary_app_lib"
version = "0.7.2"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
tokio-diesel = {git="https://github.com/mehcode/tokio-diesel.git", branch="master"}
chrono = "0.4"
rusoto_core = {version = "0.46", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.46", default_features = false, features=["rustls"]}
sts_profile_auth = "0.6"
s3-ext = "0.2"
rand = "0.8"
log = "0.4"
url = "2.2"
dotenv = "0.15"
futures = "0.3"
rayon = "1.5"
jwalk = "0.6"
structopt = "0.3"
crossbeam-channel = "0.5"
parking_lot = "0.11"
crossbeam-utils = "0.8"
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = {version = "1.4", default_features = false}
difference = "2.0"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0"
tokio = {version="1.2", features=["full"]}
derive_more = "0.99"
envy = "0.4"
smartstring = "0.2"
smallvec = "1.6"
deadqueue = "0.2"
diesel-derive-newtype = "0.1"
rweb = {version="0.11", features=["openapi"]}
stack-string = { version="0.2", features=["diesel_types", "rweb-openapi"] }
stdout-channel = "0.4"

[dev-dependencies]
tempdir = "0.3"
